[package]
name = "pltfrm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.32", features=["derive"] }
serde_json = { version = "1.0", features=["alloc"] }
serde = { version = "1.0.152", features=["alloc", "derive"] }
