#!/bin/bash

VENV="venv"

python -m pip install pip==22.3.1 pip-tools==6.11.0 --no-cache

if [ ! -d "./$VENV" ]; then
    python -m venv ./$VENV
fi

source ./$VENV/bin/activate

pip install -e ".[dev]"
